spring:
  application:
    name: TestCalculator
  port: 8080
  datasource:
    url: jdbc:postgresql://host.docker.internal:5433/automation_testing?currentSchema=calculator
    username: zezin
    password: qwerty123

flyway:
  user: zezin
  password: qwerty123
  schemas: calculator
  default-schema: calculator
  locations: classpath:db/migration/calculator
  url: jdbc:postgresql://host.docker.internal:5433/automation_testing?currentSchema=calculator